# Generated by Django 6.0 on 2025-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField(null=True)),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('aqi_category', models.CharField(max_length=20)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
